WHITESPACE  = _{ " " | "\t" | "\n" }

term        = @{ "\"" ~ ("\\" ~ ANY | !"\"" ~ ANY)* ~ "\"" }
nonterm     = @{ "'"  ~ ("\\" ~ ANY | !"'" ~ ANY)*  ~ "'" }
comment     = @{ "`"  ~ ("\\" ~ ANY | !"`" ~ ANY)*  ~ "`" }
empty       = @{ "!" }

sequence    =  { "[" ~ excpt_expr* ~ "]" }
stack       =  { "{" ~ comma_list ~ "}" }
choice      =  { "<" ~ comma_list ~ ">" }
comma_list  = _{ excpt_expr ~ ("," ~ excpt_expr)* }

simple_expr = _{ term | nonterm | comment | sequence | stack | choice | empty }
qmark       =  { "?" }
opt_expr    =  { simple_expr ~ qmark? }
rpt_expr    =  { opt_expr ~ ("*" ~ opt_expr)? }

lbox_expr   =  { rpt_expr ~ ("#" ~ rpt_expr)? }

excpt_expr  = { lbox_expr ~ ("^" ~ lbox_expr)? }

root_expr   =  { excpt_expr+ }
input       = _{ root_expr ~ EOI }
